# Generated by Django 5.1.4 on 2024-12-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='papers/')),
                ('year', models.IntegerField()),
                ('url', models.URLField(blank=True, null=True)),
                ('further_information', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
