# Generated by Django 5.1.4 on 2024-12-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
